[package]
name = "toolbelt"
version = "0.1.0"
authors = ["Alexander Czernay <alexander@czernay.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
globwalk = "0.8"
log = "0.4.8"
Inflector = "0.11.4"